### ISSUE TITLE
Test mode

### ISSUE THREAD

**Issue by dT231** [fbricker/openfl-admob#4]
Is it possible to show ad in the test mode?

**Comment by fbricker** [comment]
Hi, on iOS version, it automatically sets testing mode when using the simulator.
For Android, it's still unimplemented, but I think I'll implement this option soon (unless someone sends a pull request before I do it).

**Comment by JoeCreates** [comment]
At the moment, when trying to test on iOS, ads are not shown because the device needs to be added to test devices. Can you suggest how we are supposed to add test devices?

**Comment by fbricker** [comment]
Hi, this is strange. I always get test ADS on iOS simulator and on iOS devices I get real ads.
Maybe you should check your AdMob panel to see if the package ID on your ad unit, fits the package ID of you app.

Anyway, so far there's no API implemented on the extension to add test devices, but I may add this soon.

**Comment by JoeCreates** [comment]
Hmm . . . it seems like we're actually just never seeing ads on ios. Even tried adding the device id to test devices in the mm and rebuilding.

**Comment by fbricker** [comment]
Have you tried on simulator?

**Comment by Andrew3216767** [comment]
Hey Federico, could you please check your Skype? I contacted you on the problem!

**Comment by fbricker** [comment]
Hi, please leave your details about the issue here, so that the information remains public to the rest of the users. Also, I don't provide support though Skype (as I do this on my free time).

**Comment by fbricker** [comment]
Hi guys, I've just published a new version of the extesion including the ability to enable test ads.
Just call
```haxe
AdMob.enableTestingAds();
```
Before calling init and it'll always display test ads.

This version also fixes one bug in iOS interstitials, so I encourage you to upgrade.

Thanks!
