### ISSUE TITLE
Some error in android build.

### ISSUE THREAD

**Issue by MadnessRussian** [fbricker/openfl-admob#7]
Haxe 3.1.3 , lime 1.5.6,openfl 2.0
Hi! After install and include to project libs :openfl-gps-lib ,openfl-admob i can't build android version
i see this error http://imgur.com/YC3pUdX

**Comment by fbricker** [comment]
Hi, did you downloaded 'Google Play Services Library' from the android package manager?
If not, please read how to do that on Read more at https://github.com/fbricker/openfl-gps-lib

**Comment by fbricker** [comment]
Also, I think you may need to upgrade your lime version as well, since old lime versions does not allow the extension to import a library from android sdk path.

**Comment by MadnessRussian** [comment]
Thanks,i did this and get android app. But i don't see ads.
code :
AdMob.initAndroid("bannerID","interId", GravityMode.TOP);
AdMob.showBanner();

in simple openfl project.

**Comment by fbricker** [comment]
Have you replaced the strings "bannerID" and "InterID" with real banner IDs from google Admob?
If not, you need to create some banners on google admob console first and replace those string with the real IDs.

If yes, you may need to wait for a couple if seconds before admob loads the ads from the internet before you can see them (you should also check that your phone has internet connection). Otherwise you won't see ads.

**Comment by MadnessRussian** [comment]
Yes,i use a real id's,have internet connection ( upload files to phone with wi-fi) 
but i don't see ad's
prioject:
https://github.com/MadnessRussian/Openfl_test_ads2

**Comment by MadnessRussian** [comment]
in my phone log i see :
1)) unable to find class rederenced in signature (landroid/support/v4/app/fragment)
2) could not find class 'android.support.v4.app.FragmentActivity',referenced from method com.google.android.gms.common.googleplayservisesUtil.showerrordialogfragment.

**Comment by fbricker** [comment]
Oh, It looks like you're missing  the "Android Support Library" - you can get it from the Android SDK Manager (under the extras section).

You can check steps here: https://github.com/fbricker/openfl-admob#how-to-install

PS: I've tried you sample app in my phone and displays works for me (so I guess it's just a matter of installing the android support library).

Please let me know if this solves your issue :)

**Comment by MadnessRussian** [comment]
I have this library http://imgur.com/9tLrEEC
Maybe i must include this in to my project?

**Comment by fbricker** [comment]
Hi, here I send you my setup (android and haxe libraries installed).
In my case your example works right out of the box: just doing a git clone and lime test android do the trick.

![captura de pantalla 2015-03-07 a las 12 23 25](https://cloud.githubusercontent.com/assets/1865352/6541854/44b46748-c4c5-11e4-9376-aed66cad0809.png)

![captura de pantalla 2015-03-07 a las 12 23 38](https://cloud.githubusercontent.com/assets/1865352/6541855/53775aa6-c4c5-11e4-8f6b-c93deb6937b5.png)

![captura de pantalla 2015-03-07 a las 12 28 35](https://cloud.githubusercontent.com/assets/1865352/6541861/85ba0892-c4c5-11e4-8508-c830f3b628db.png)

![captura de pantalla 2015-03-07 a las 12 24 51](https://cloud.githubusercontent.com/assets/1865352/6541857/62248844-c4c5-11e4-87c6-d2056c50ea35.png)

**Comment by MadnessRussian** [comment]
Thanks for you help! Problem - in my phone os,i have custom android os without of official android servises :)

**Comment by fbricker** [comment]
Oh, shame on google then. I think google should consider to begin implementing less painful APIs for developers. I mean: AdMob SDK should work on any android device, no matter if the phone has google services installed or not.

At least you figured out the issue :)
